service: gql-2022-02
# https://rj07ty7re4.execute-api.us-east-1.amazonaws.com/dev/gql
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 12
  stage: dev
  profile: default
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:

  gql:
    handler: gql.gql
    description: graphql implementation
    environment:
      ES_DOMAIN: ${file(./config.json):ES_DOMAIN}
    events:
      - http:
          path: gql
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - jwt_token
            allowCredentials: false
