type Query {
  move(id: String!): Move
  allMoves(page: Int, itemsPerPage: Int): MovePage
  pokemon(id: String!): Pokemon
  allPokemon(page: Int, itemsPerPage: Int): PokemonPage
  test(message: String!): TestObject
  testNoParam: TestObject
}
